--- #YAML:1.0
name:               Text-PageLayout
version:            0.01
abstract:           Distribute paragraphs onto pages, with headers and footers.
author:
    - Moritz Lenz <moritz@faui2k3.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moo:           0.091011
    Scalar::Util:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
